const players = [
  {
    playerId: 1,
    name: "Jan Oblak",
    position: "GOALKEEPER",
    club: "Atlético Madrid",
    price: 6.1,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/250012069.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 2,
    name: "Sergio Escudero",
    position: "DEFENDER",
    club: "Sevilla",
    price: 6.0,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/95803.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 3,
    name: "Alex Telles",
    position: "DEFENDER",
    club: "Porto",
    price: 12.4,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/95803.jpg",
    minutesPlayed: 450,
    goals: 10,
    assists: 2,
    yellowCards: 0,
    redCards: 0,
    goalsConceded: 0
  },

  {
    playerId: 4,
    name: "Dani Alves",
    position: "DEFENDER",
    club: "Juventus",
    price: 6.1,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/250017925.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 5,
    name: "Mariano Ferreira",
    position: "DEFENDER",
    club: "Sevilla",
    price: 6.0,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/250049643.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 6,
    name: "Patrice Evra",
    position: "DEFENDER",
    club: "Juventus",
    price: 5.6,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/68468.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 7,
    name: "Mesut Özil",
    position: "MIDFIELDER",
    club: "Arsenal",
    price: 9.3,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/103697.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 8,
    name: "Riyad Mahrez",
    position: "MIDFIELDER",
    club: "Leicester",
    price: 8.1,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/250070687.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 9,
    name: "Arda Turan",
    position: "MIDFIELDER",
    club: "Barcelona",
    price: 7.1,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/74850.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 10,
    name: "Joshua Kimmich",
    position: "MIDFIELDER",
    club: "FC Bayern",
    price: 5.5,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/250070417.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 11,
    name: "André Silva",
    position: "MIDFIELDER",
    club: "Porto",
    price: 6.9,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/250042521.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 12,
    name: "Lionel Messi",
    position: "FORWARD",
    club: "Barcelona",
    price: 12.4,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/95803.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 13,
    name: "Edinson Cavani",
    position: "FORWARD",
    club: "PSG",
    price: 9.3,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/1905813.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  },
  {
    playerId: 14,
    name: "Dries Mertens",
    position: "FORWARD",
    club: "Napoli",
    price: 6.9,
    image: "http://img.uefa.com/imgml/TP/players/1/2017/324x324/250019924.jpg",
    minutesPlayed: 9,
    goals: 5,
    assists: 3,
    yellowCards: 1,
    redCards: 0,
    goalsConceded: 0
  }
]
export default players
